### ISSUE TITLE
Project broke after Gradle plugin 4.1.0 update

### ISSUE THREAD

**Issue by Glennmen** [SUPERCILEX/version-orchestrator#7]
Dependabot tried to make an update to Gradle plugin version 4.1.0 but the build failed. 
I quickly found out that this was because of version-master, I tested locally by updating to the latest snapshot version and this seemed to fix it.
However I don't want to use the snapshot version in my project, would it be possible to make a new release or are there still open issues?

**Comment by SUPERCILEX** [comment]
I was hoping to be able to stabilize the AGP version the plugin depends on, but it looks like that won't happen for a while since they're still breaking their APIs. That just means this plugin won't work with AGP 4.2.x and I'll have to release a breaking change for that.

In the meantime, I made an 0.7.0 release with breaking changes, renaming all instances of master to orchestrator to be more inclusive.

**Comment by SUPERCILEX** [comment]
Please let me know if there are any issues.
